## 重定向与请求历史

默认情况下，除了 `HEAD`, Requests 会自动处理所有重定向。

可以使用响应对象的 `history` 方法来追踪重定向。

`Response.history` 是一个 `Response` 对象的列表，为了完成请求而创建了这些对象。
这个对象列表按照从最老到最近的请求进行排序。

- 例如，Github 将所有的 HTTP 请求重定向到 HTTPS：

```python
 r = requests.get('http://github.com')

 r.url
'https://github.com/'

 r.status_code
200

 r.history
[<Response [301]>]
```

如果你使用的是`GET、OPTIONS、POST、PUT、PATCH 或者 DELETE`

那么可以通过 `allow_redirects` 参数禁用重定向处理：

```python
 r = requests.get('http://github.com', allow_redirects=False)
 r.status_code
301
 r.history
[]
```

如果使用了 `HEAD`，也可以启用重定向：

```python
 r = requests.head('http://github.com', allow_redirects=True)
 r.url
'https://github.com/'
 r.history
[<Response [301]>]
```

## 超时

可以告诉 `requests` 在经过以 `timeout` 参数设定的秒数时间之后停止等待响应。
基本上所有的生产代码都应该使用这一参数。
如果不使用，程序可能会永远失去响应：

```python
 requests.get('http://github.com', timeout=0.001)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
requests.exceptions.Timeout: HTTPConnectionPool(host='github.com', port=80): Request timed out. (timeout=0.001)
```

### 注意

`timeout` 仅对连接过程有效，与响应体的下载无关。 
timeout 并不是整个下载响应的时间限制，而是如果服务器在 timeout 秒内没有应答，将会引发一个异常（更精确地说，是在 timeout 秒内没有从基础套接字上接收到任何字节的数据时）

## 错误与异常

1. 遇到网络问题（如：`DNS 查询失败`、`拒绝连接`等）时，`Requests` 会抛出一个 `ConnectionError` 异常。

2. 如果 `HTTP` 请求返回了不成功的状态码， `Response.raise_for_status()` 会抛出一个 `HTTPError` 异常。

3. 若请求超时，则抛出一个 `Timeout` 异常。

4. 若请求超过了设定的最大重定向次数，则会抛出一个 `TooManyRedirects` 异常。

所有Requests显式抛出的异常都继承自 `requests.exceptions.RequestException`
